from .application1 import Application1
from .application2 import Application2
from .applicationMVA import ApplicationMVA
from .application import Application
from .applicationsCluster import AppsCluster
from .sockshopmicroservice import SockShopMicroservice
from .order import Order
from .cartspost import CartsPost
from .cartscatalogue import CartsCatalogue
from .cartsdelete import CartsDelete
from .cartsutil import CartsUtil
from .payment import Payment
from .registration import Registration
from .user import User
from .login import Login
